name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.20', '1.21']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        # Build the src module (main library)
        cd src
        go build -v .
        cd ..

        # Build the app modules
        cd app/convbin
        go build -v .
        cd ../..

        # Build test imports
        cd test_import
        go build -v .
        cd ..

        cd test_import2
        go build -v .
        cd ..

    - name: Test
      run: |
        # Test the src module (main library)
        cd src
        go test -v .
        cd ..
